In [1]:
import torch
import torch.nn as nn

In [2]:
randomimage = torch.rand((3, 100, 150))

In [3]:
randomimage

tensor([[[0.2580, 0.7481, 0.5735,  ..., 0.8887, 0.9089, 0.6511],
         [0.9633, 0.7706, 0.3409,  ..., 0.1863, 0.6161, 0.2153],
         [0.2609, 0.5669, 0.6159,  ..., 0.0488, 0.0340, 0.4791],
         ...,
         [0.2877, 0.8229, 0.9152,  ..., 0.9684, 0.9354, 0.1222],
         [0.1916, 0.5251, 0.8942,  ..., 0.1941, 0.6207, 0.4966],
         [0.1748, 0.7617, 0.5933,  ..., 0.3307, 0.8909, 0.7600]],

        [[0.8299, 0.4437, 0.9840,  ..., 0.2183, 0.7729, 0.9232],
         [0.7445, 0.8798, 0.9952,  ..., 0.4516, 0.3758, 0.3491],
         [0.4537, 0.2647, 0.1802,  ..., 0.6581, 0.7005, 0.9242],
         ...,
         [0.6107, 0.1237, 0.9462,  ..., 0.7119, 0.1873, 0.2384],
         [0.2552, 0.7997, 0.1605,  ..., 0.3587, 0.4156, 0.6832],
         [0.1657, 0.0436, 0.5725,  ..., 0.3944, 0.9709, 0.9789]],

        [[0.5477, 0.2925, 0.8286,  ..., 0.0825, 0.7374, 0.9807],
         [0.0622, 0.4022, 0.6170,  ..., 0.4563, 0.0986, 0.3629],
         [0.7891, 0.3931, 0.4362,  ..., 0.4295, 0.6597, 0.

In [4]:
randomimage.size()

torch.Size([3, 100, 150])

In [5]:
conv2d = nn.Conv2d(3, 1, (3,3), padding="same")

In [9]:
output = conv2d(randomimage.unsqueeze(0))

In [10]:
output

tensor([[[[ 0.0247, -0.3376, -0.3023,  ..., -0.0899, -0.0764,  0.2151],
          [-0.4841, -0.6529, -0.7425,  ..., -0.5821, -0.8505, -0.3410],
          [-0.2463, -0.4760, -0.8349,  ..., -0.5313, -0.4612, -0.2159],
          ...,
          [-0.3464, -0.4520, -0.1392,  ..., -0.5409, -0.4208, -0.2646],
          [-0.1394, -0.4963, -0.3122,  ..., -0.3240, -0.4546, -0.1702],
          [ 0.0627, -0.1421, -0.0869,  ..., -0.3635, -0.2450,  0.0121]]]],
       grad_fn=<ConvolutionBackward0>)

In [11]:
output.size()

torch.Size([1, 1, 100, 150])

In [25]:
maxpool2d = nn.MaxPool2d((100,3))

In [26]:
output2 = maxpool2d(output)

In [27]:
output2.size()

torch.Size([1, 1, 1, 50])

In [28]:
output2

tensor([[[[ 0.1053, -0.0099,  0.0009,  0.0936,  0.0917,  0.1361,  0.1175,
            0.0570,  0.1652,  0.0485,  0.0616, -0.1439,  0.0034,  0.0906,
            0.0977,  0.1577,  0.1692, -0.0375,  0.1737,  0.2130,  0.1218,
            0.0681,  0.1301, -0.0025,  0.0187,  0.1317, -0.0115, -0.0958,
            0.2136,  0.1716,  0.1397,  0.1516, -0.0007,  0.0176, -0.0179,
            0.0188,  0.1014,  0.1359,  0.0297,  0.2032,  0.2257,  0.0412,
            0.0379, -0.0026,  0.0449,  0.1375, -0.0769,  0.0621, -0.0976,
            0.2440]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)

In [29]:
torch.squeeze(output2)

tensor([ 0.1053, -0.0099,  0.0009,  0.0936,  0.0917,  0.1361,  0.1175,  0.0570,
         0.1652,  0.0485,  0.0616, -0.1439,  0.0034,  0.0906,  0.0977,  0.1577,
         0.1692, -0.0375,  0.1737,  0.2130,  0.1218,  0.0681,  0.1301, -0.0025,
         0.0187,  0.1317, -0.0115, -0.0958,  0.2136,  0.1716,  0.1397,  0.1516,
        -0.0007,  0.0176, -0.0179,  0.0188,  0.1014,  0.1359,  0.0297,  0.2032,
         0.2257,  0.0412,  0.0379, -0.0026,  0.0449,  0.1375, -0.0769,  0.0621,
        -0.0976,  0.2440], grad_fn=<SqueezeBackward0>)

In [30]:
randomimage.size()

torch.Size([3, 100, 150])

In [32]:
randomimage2 = randomimage.unsqueeze(0)

In [33]:
randomimage2.size()

torch.Size([1, 3, 100, 150])

In [34]:
randomimage3 = torch.permute(randomimage2, (0,2,3,1))

In [35]:
randomimage3

tensor([[[[0.2580, 0.8299, 0.5477],
          [0.7481, 0.4437, 0.2925],
          [0.5735, 0.9840, 0.8286],
          ...,
          [0.8887, 0.2183, 0.0825],
          [0.9089, 0.7729, 0.7374],
          [0.6511, 0.9232, 0.9807]],

         [[0.9633, 0.7445, 0.0622],
          [0.7706, 0.8798, 0.4022],
          [0.3409, 0.9952, 0.6170],
          ...,
          [0.1863, 0.4516, 0.4563],
          [0.6161, 0.3758, 0.0986],
          [0.2153, 0.3491, 0.3629]],

         [[0.2609, 0.4537, 0.7891],
          [0.5669, 0.2647, 0.3931],
          [0.6159, 0.1802, 0.4362],
          ...,
          [0.0488, 0.6581, 0.4295],
          [0.0340, 0.7005, 0.6597],
          [0.4791, 0.9242, 0.3703]],

         ...,

         [[0.2877, 0.6107, 0.0702],
          [0.8229, 0.1237, 0.4637],
          [0.9152, 0.9462, 0.9324],
          ...,
          [0.9684, 0.7119, 0.1523],
          [0.9354, 0.1873, 0.2159],
          [0.1222, 0.2384, 0.0429]],

         [[0.1916, 0.2552, 0.6978],
          [0.5251

In [36]:
randomimage3.size()

torch.Size([1, 100, 150, 3])